# Generated by Django 4.1.8 on 2023-05-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_player_tournament_points'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1_score', models.CharField(max_length=5)),
                ('set2_score', models.CharField(max_length=5)),
                ('set3_score', models.CharField(blank=True, max_length=5, null=True)),
                ('pair1', models.ManyToManyField(related_name='matches_as_pair1', to='players.player')),
                ('pair2', models.ManyToManyField(related_name='matches_as_pair2', to='players.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('winner', models.ManyToManyField(related_name='won_matches', to='players.player')),
            ],
        ),
    ]
