# Generated by Django 4.1.8 on 2023-05-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userPoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
