# Generated by Django 4.1.8 on 2023-05-28 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('points', models.IntegerField()),
                ('winrate', models.FloatField()),
                ('price', models.FloatField()),
                ('users', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
