# Generated by Django 4.1.8 on 2023-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament_points',
            field=models.IntegerField(default=0),
        ),
    ]
