# Generated by Django 4.1.8 on 2023-06-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
    ]
