# Generated by Django 4.1.8 on 2023-06-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
