# Generated by Django 4.1.8 on 2023-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
